# Generated by Django 3.2.25 on 2025-03-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='election_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='election_name',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
