# Generated by Django 3.2.25 on 2025-03-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20250310_0119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='election_date',
        ),
    ]
